---
# tasks file for pycharm

- name: install tar on Fedora 24
  dnf:
    name: tar
    state: present
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version == "24"

- name: Create directories for RubyMine
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ rubymine_download_directory }}"
  - "{{ rubymine_install_directory }}"
  - "{{ rubymine_desktop_file_location | dirname }}"


- name: Download RubyMine plugins
  get_url:
    url: "{{ rubymine_plugin_download_mirror }}{{ item }}"
    dest: "{{ rubymine_download_directory }}"
  register: rubymine_plugins
  with_items: "{{ rubymine_plugins }}"

- name: Install RubyMine
  unarchive:
    copy: no
    src: "{{ rubymine_download_url}}"
    dest: "{{ rubymine_install_directory }}"
    creates: "{{ rubymine_location }}/bin/rubymine.sh"

- name: Install RubyMine Plugins
  unarchive:
    src: "{{ item.dest }}"
    dest: "{{ rubymine_location }}/plugins"
  with_items: "{{ rubymine_plugins.results }}"

- name: Create RubyMine desktop entry
  template:
    src: rubymine.desktop.j2
    dest: "{{ rubymine_desktop_file_location }}"
